version: '3'
services:
  hello-world:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:8080"
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=popeye
